USE BookStoreDb;
GO

--TRIGGER PARA INSERTAR LOS NUEVOS PRECIOS EN EL HISTORICO
CREATE TRIGGER TRG_INSERT_HISTORY_PRICE
ON EDITION_PRICE
AFTER INSERT, UPDATE
AS BEGIN
	INSERT INTO HISTORY_PRICE
	SELECT EDITION_ID, GETDATE(), PRICE
	FROM INSERTED;
END;
GO